version: 1.0
mode: prod

jwt_key: my_secret_key

database:
  name: test
  user: Dunty
  password: 123123Dunty
  ip: 192.168.136.130:3306

redis:
  ip: 192.168.136.130:6379
  password: 123123Dunty
  db: 1 
  enable_tls: false

nsq:
  nsqd_ip: 127.0.0.1:4150
  nsqlookupd_ip: 192.168.136.128:4161
  max_retry: 3
  retry_time: 1000
  # Set error_redis_key to null, if no need to save error msg.
  error_redis_key: nsq_error
  # Set error_save_time to 0 to permanently store the error message.
  error_save_time: 86400
  